# Generated by Django 5.2.6 on 2025-09-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('done', models.BooleanField(default=False, verbose_name='Completada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
            ],
        ),
    ]
